#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Extract substantive reports from orphaned wt-worker-* dashboards

.DESCRIPTION
    Phase 3.2 of issue #1429: Scan all wt-worker-* dashboards, extract
    substantive content, and save to docs/history/worker-reports/

.NOTES
    Issue: #1429
    Phase: 3.2 - Extraction batch
    Author: Claude Code (myia-po-2023)
    Date: 2026-04-17
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

# Constants
$WorkspaceRoot = "D:/Dev/roo-extensions"
$OutputRoot = "$WorkspaceRoot/docs/history/worker-reports"
$DashboardPrefix = "workspace-wt-worker-"

# Categories for classification
$Categories = @{
    "fix" = "fixes"
    "test" = "tests"
    "validat" = "tests"
    "ci" = "tests"
    "audit" = "analyses"
    "investig" = "analyses"
    "coordinat" = "meta"
    "meta" = "meta"
    "dispatch" = "meta"
    "report" = "meta"
}

# Filter patterns for substantive content
$SubstantivePatterns = @(
    "\[DONE\]",
    "\[RESULT\]",
    "\[REPORT\]",
    "PR #\d+",
    "issue #\d+",
    "[a-f0-9]{7,40}",  # Commit SHAs
    "merg[ée]ed?",
    "commit",
    "test",
    "fix",
    "implement"
)

function Test-SubstantiveContent {
    param([string]$Content)

    # Must be > 100 chars
    if ($Content.Length -lt 100) {
        return $false
    }

    # Must match at least one substantive pattern
    foreach ($Pattern in $SubstantivePatterns) {
        if ($Content -match $Pattern) {
            return $true
        }
    }

    return $false
}

function Get-DashboardMachine {
    param([string]$DashboardKey)

    if ($DashboardKey -match "wt-worker-(myia-[a-z0-9-]+)") {
        return $matches[1]
    }
    return "unknown"
}

function Get-ReportCategory {
    param([string]$Content)

    foreach ($Pattern in $Categories.Keys) {
        if ($Content -match $Pattern) {
            return $Categories[$Pattern]
        }
    }
    return "misc"
}

function Extract-Entities {
    param([string]$Content)

    $Entities = @{
        PRs = @()
        Issues = @()
        Commits = @()
    }

    # Extract PR numbers
    $Content | Select-String -Pattern "PR #(\d+)" -AllMatches | ForEach-Object {
        $_.Matches | ForEach-Object {
            $Entities.PRs += $_.Groups[1].Value
        }
    }

    # Extract issue numbers
    $Content | Select-String -Pattern "issue #(\d+)" -AllMatches | ForEach-Object {
        $_.Matches | ForEach-Object {
            $Entities.Issues += $_.Groups[1].Value
        }
    }

    # Extract commit SHAs (7+ hex chars)
    $Content | Select-String -Pattern "\b([a-f0-9]{7,40})\b" -AllMatches | ForEach-Object {
        $_.Matches | ForEach-Object {
            $Entities.Commits += $_.Groups[1].Value
        }
    }

    return $Entities
}

function Format-ReportMarkdown {
    param(
        [string]$DashboardKey,
        [string]$Content,
        [datetime]$Timestamp,
        [hashtable]$Entities
    )

    $Machine = Get-DashboardMachine -DashboardKey $DashboardKey
    $Category = Get-ReportCategory -Content $Content

    $Md = @"
# Worker Report - $DashboardKey

**Source Dashboard:** `$DashboardKey`
**Machine:** $Machine
**Extracted:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
**Dashboard Last Modified:** $($Timestamp.ToString("yyyy-MM-dd HH:mm:ss"))

## Entities

### Pull Requests
$($Entities.PRs | ForEach-Object { "- PR #$_" } | Out-String)

### Issues
$($Entities.Issues | ForEach-Object { "- Issue #$_" } | Out-String)

### Commits
$($Entities.Commits | Select-Object -Unique | ForEach-Object { "- ``$_``" } | Out-String)

## Content

$Content

---

**Generated by:** Extract-WorkerReports.ps1 (Issue #1429 Phase 3.2)
"@

    return $Md
}

function Invoke-Extraction {
    Write-Host "=== Phase 3.2: Worker Reports Extraction ===" -ForegroundColor Cyan
    Write-Host "Scanning orphaned wt-worker-* dashboards..." -ForegroundColor Yellow

    # Get all dashboards via roosync_dashboard list
    # Note: This would be called via MCP in actual execution
    # For now, we'll create a mock structure

    $DashboardList = @(
        # This would be populated from roosync_dashboard list
        # filtering for keys starting with "workspace-wt-worker-"
    )

    $Stats = @{
        Total = 0
        Processed = 0
        Substantive = 0
        Skipped = 0
    }

    Write-Host "`nStatistics:" -ForegroundColor Green
    Write-Host "  Total dashboards: $($Stats.Total)"
    Write-Host "  Processed: $($Stats.Processed)"
    Write-Host "  Substantive reports extracted: $($Stats.Substantive)"
    Write-Host "  Skipped (trivial): $($Stats.Skipped)"
}

# Run extraction
Invoke-Extraction
