$sessions = @("495bfaa8-cc99-49c1-a45d-f80086b08070.jsonl","5bd5b064-930a-4231-bf5e-53ce5c0a69c9.jsonl","90b2e29b-bc8c-45a9-bb2e-db272a0b7928.jsonl","8238ddb3-a2a8-4524-ae6f-5ddf198ae3d7.jsonl","67a777e5-f176-4015-ad2a-bc04f3232130.jsonl")
$basePath = "$env:USERPROFILE/.claude/projects"; Write-Host "=== ANALYSE DES SESSIONS CLAUDE ===" -ForegroundColor Cyan; Write-Host ""
foreach ($sessionFile in $sessions) { $fullPath = Get-ChildItem -Path $basePath -Recurse -Filter $sessionFile | Select-Object -First 1; if (-not $fullPath) { Write-Host "Session non trouvee: $sessionFile" -ForegroundColor Red; continue }; Write-Host "Session: $($sessionFile)" -ForegroundColor Yellow; Write-Host "Chemin: $($fullPath.FullName)"; Write-Host "Taille: $([math]::Round($fullPath.Length / 1MB, 2)) MB"; Write-Host "Derniere modification: $($fullPath.LastWriteTime)"
$lines = Get-Content $fullPath.FullName -Encoding UTF8; $totalMessages = $lines.Count; $userMessages = 0; $assistantMessages = 0; $toolMessages = 0; $errors = @(); $toolsUsed = @{}
foreach ($line in $lines) { try { $msg = $line | ConvertFrom-Json; if ($msg.type -eq "user") { $userMessages++ } elseif ($msg.type -eq "assistant") { $assistantMessages++; if ($msg.message.content) { foreach ($contentItem in $msg.message.content) { if ($contentItem.type -eq "tool_use") { $toolName = $contentItem.name; if ($toolsUsed.ContainsKey($toolName)) { $toolsUsed[$toolName]++ } else { $toolsUsed[$toolName] = 1 } } } } } } catch { } }
foreach ($line in $lines) { try { $msg = $line | ConvertFrom-Json; if ($msg.type -eq "user" -and $msg.message.content) { foreach ($contentItem in $msg.message.content) { if ($contentItem.type -eq "tool_result" -and $contentItem.is_error) { $errors += "Tool error: $($contentItem.tool_use_id)" } } } } catch { } }
$toolMessages = ($toolsUsed.Values | Measure-Object -Sum).Sum; Write-Host "Messages totaux: $totalMessages"; Write-Host "  - User: $userMessages"; Write-Host "  - Assistant: $assistantMessages"; Write-Host "  - Tool calls: $toolMessages"
if ($errors.Count -gt 0) { Write-Host "Erreurs: $($errors.Count)" -ForegroundColor Red } else { Write-Host "Erreurs: 0" -ForegroundColor Green }
if ($toolsUsed.Count -gt 0) { Write-Host "Outils utilises (top 10):"; $toolsUsed.GetEnumerator() | Sort-Object Value -Descending | Select-Object -First 10 | ForEach-Object { Write-Host "  - $($_.Key): $($_.Value)" } }
$status = if ($errors.Count -eq 0) { "SUCCESS" } elseif ($errors.Count -lt 5) { "PARTIAL" } else { "FAILED" }; Write-Host "Statut: $status" -ForegroundColor $(if ($status -eq "SUCCESS") { "Green" } elseif ($status -eq "PARTIAL") { "Yellow" } else { "Red" }); Write-Host ""; Write-Host "---" -ForegroundColor Gray; Write-Host "" }
